### ISSUE TITLE
Night Mode

### ISSUE THREAD

**Issue by khalid-hussain** [khalid-hussain/HisnulMuslim#25]
Settings in the Preferences and  in the menus of both activities have been added. Just the implementation is left. Night Mode should:
1) Turn the Action Bar black. In essence, this means colorPrimary and colorPrimaryDark would be black or the former complete black and the latter a little less black.
2) The ListView in DuaGroup activity should be inverted and the circle around the numbers should disappear or become a really dark gray/black.
3) The above would apply to the DuaDetail activity but a dark gray should be used as well to be able to identify the cards.

**Comment by ahmedre** [comment]
you can't really change `colorPrimary` and `colorPrimaryDark` after the fact, but we can basically manually (and tediously) achieve the same effect by changing the `ToolBar` background colors and tinting the icons.

i mentioned this to one of the engineers working on the support library and he raised it as a feature request, so hopefully one day it becomes easier.

i'll take a shot at this.

**Comment by khalid-hussain** [comment]
Man, it looks really good! 

Just a couple of related questions:

1) Is it possible to change a color in the styles.xml file dynamically? I ask this, because on Lollipop, 'primaryDark' needs to be changed to ensure "full" night mode on any activity due to the colored status bar. 'colorAccent' as well to highlight search bar and text selection in search. This would also help that bouncy limiter to tell the users they have reached the end of the list.

2) Just to confirm, each activity would need to have this manually crafted according to its contents, right?

JazakAllahu khayran.

**Comment by ahmedre** [comment]
1. not in the way you want to, nope (that's what i was saying that the engineer working on the support lib at google said he'd file a request for it, so you could dynamically set an actual theme afterwards). you can't dynamically change the theme without killing the activity. if you don't mind killing the activity, then you can (before `super.onCreate`) choose which theme to set - a dark theme or a light theme. otherwise, without killing the activity, you have to fake it (as i've done in this patch).
2. yes, unfortunately. if the code is the same, you can extract it out to a common class or common utility methods or what not.

**Comment by khalid-hussain** [comment]
Okay, can changing 'primaryDark' be faked?

**Comment by ahmedre** [comment]
nope, not unless you kill the activity :)
